utils::globalVariables(c("es", "se", ".", "condition", "study", "NNT",
                         "studlab", "rstudent", "is.infl",
                         "dffits", "cook.d", "cov.r",
                         "tau2.del", "QE.del", "weight",
                         "lower", "upper", "value", "y",
                         "group.names", "which.run",
                         "g", "model", "Analysis", "funcs2",
                         "excluded", "yi", "vi", "error", ".g",
                         ".log_rr", ".id", "rr", "m.ThreeLevel.g",
                         "mCHE.g", "event", "mCombined", "method.tau.meta",
                         "multi.study", "TE", "condition_arm1", 
                         "condition_arm2", "multi_arm1", "n.var.arm1", 
                         "n.var.arm2", "seTE", "tau2", ".TE",
                         ".seTE", ".studlab", "x", "multi_arm2",
                         "N1", "N2", "N", "g1", "multi", "out1", 
                         "out2", "measurement"))
