utils::globalVariables(c("es", "se", ".", "condition", "study", "NNT",
                         "studlab", "rstudent", "is.infl",
                         "dffits", "cook.d", "cov.r",
                         "tau2.del", "QE.del", "weight",
                         "lower", "upper", "value", "y",
                         "group.names", "which.run",
                         "g", "model", "Analysis", "funcs2",
                         "excluded", "yi", "vi", "error", ".g",
                         ".log_rr", ".id", "rr", "m.ThreeLevel.g",
                         "mCHE.g"))
